apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sub-pc-frames-pvc
  namespace: semseg
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pc-frames-pvc
  namespace: semseg
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: segments-pvc
  namespace: semseg
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi

