apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: semseg
resources:
  - 00-namespace.yaml
  - 03-pvc.yaml
  - 05-redis.yaml
  - 20-convert.yaml
  - 40-part-labeler.yaml
  - 50-redactor.yaml
  - 60-analytics.yaml
  - 70-results-api.yaml
  - 80-qa-web.yaml